spring:
  application:
    name: nyo
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none   # 자동생성 X
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true

server:
  port: 8080